version: '3'
services:
  oracle:
    image: sath89/oracle-12c
    ports:
        - 1525:1525
    environment:
        - ORACLE_ALLOW_REMOTE=true
        - WEB_CONSOLE=false
        - ORACLE_SID=xe  
  rabbitmq:
    image: rabbitmq:management
    expose:
     - "5672"
    ports:
     - "15672:15672"
     - "5672:5672"
    networks:
      - default
  zipkin:
    image: "openzipkin/zipkin"
    depends_on:
     - rabbitmq
    links:
     - rabbitmq
    environment:
     - RABBIT_URI=amqp://rabbitmq
    ports:
      - "9411:9411"
    networks:
      - default
